- path: "run.runner.train.torch_compile"
  value:
    enabled: true
    parameters:
      fullgraph: true
      mode: "max-autotune-no-cudagraphs"
    compiled_autograd:
      enabled: true
      parameters:
        fullgraph: true
        mode: "max-autotune-no-cudagraphs"
