- path: "logging.tags"
  action: "remove_by_value"
  value: "256"
- path: "logging.tags"
  action: "append"
  value: "224"
- path: "common.template_size"
  value: [ 112, 112 ]
- path: "common.search_region_size"
  value: [ 224, 224 ]