!concat
- !include "_224.yaml"
- - path: "name"
    value: "MAE/H-224"
  - path: "logging.tags"
    action: "remove_by_value"
    value: "base"
  - path: "logging.tags"
    action: "append"
    value: "huge"
  - path: "model.backbone.parameters.model_name"
    value: "vit_huge_patch14_224.mae"
  - path: "model.backbone.parameters"
    action: "merge"
    value:
      drop_path_rate: 0.1