- path: "name"
  value: "DINOv2/S-224"
- path: "logging.tags"
  action: "remove_by_value"
  value: "base"
- path: "logging.tags"
  action: "append"
  value: "small"
- path: "model.backbone.parameters.model_name"
  value: "vit_small_patch14_dinov2.lvd142m"