- path: "name"
  value: "CLIP/H-378"
- path: "logging.tags"
  action: "remove_by_value"
  value: "base"
- path: "logging.tags"
  action: "append"
  value: "huge"
- path: "model.backbone.parameters"
  action: "merge"
  value:
    drop_path_rate: 0.4
- path: "run.runner.train.optimization.optimizer.per_parameter.0.lr_decay_rate"
  value: 0.9