- path: "name"
  value: "DINOv2/L-224"
- path: "logging.tags"
  action: "remove_by_value"
  value: "base"
- path: "logging.tags"
  action: "append"
  value: "large"
- path: "model.backbone.parameters.name"
  value: "ViT-L/14"
- path: "model.backbone.parameters"
  action: "merge"
  value:
    drop_path_rate: 0.1
