name: "EVA02/B-224"

logging:
  category: "LoRAT"
  tags:
    - "EVA02"
    - "base"
    - "224"

type: "LoRAT-timm"

common:
  template_size: [ 112, 112 ]
  search_region_size: [ 224, 224 ]
  template_feat_size: [ 8, 8 ]
  search_region_feat_size: &search_region_feat_size [ 16, 16 ]
  response_map_size: *search_region_feat_size
  interpolation_mode: "bilinear"
  interpolation_align_corners: false
  normalization: "openai_clip"

model:
  type: "eva"
  backbone:
    type: "timm"
    parameters:
      model_name: "eva02_base_patch14_224"

run: !include "../run.yaml"
