- path: "name"
  value: "DINOv2/S-224"
- path: "logging.tags"
  action: "remove_by_value"
  value: "base"
- path: "logging.tags"
  action: "append"
  value: "large"
- path: "model.backbone.parameters.name"
  value: "ViT-S/14"
