- path: "logging.tags"
  action: "remove"
  value: "224"
- path: "logging.tags"
  action: "append"
  value: "378"
- path:
  - "common.template_feat_size"
  - "model.template_feat_size"
  value: [ 14, 14 ]
- path: "common.template_size"
  value: [ 196, 196 ]
- path:
  - "common.response_map_size"
  - "common.search_region_feat_size"
  value: [ 27, 27 ]
- path: "common.search_region_size"
  value: [ 378, 378 ]
- path:
  - "run.data.train.transform.SiamFC_cropping.search_region.area_factor"
  - "run.data.val.transform.SiamFC_cropping.search_region.area_factor"
  value: 5.
- path: "run.runner.test.evaluator.pipeline.curation_parameter_provider.search_area_factor"
  value: 5.