!concat
- !include "evaluation.yaml"
- - path: "run.data.eval.type"
    value: "siamese_tracker_eval_vot"
  - path: "run.profiling.enabled"
    value: false
  - path: "run.data.eval"
    action: "merge"
    value:
      region_format: "rectangle"