- path: "name"
  value: "MAE/L-256"
- path: "logging.tags"
  action: "remove_by_value"
  value: "base"
- path: "logging.tags"
  action: "append"
  value: "large"
- path: "model.backbone.parameters.model_name"
  value: "vit_large_patch16_224.mae"
- path: "model.backbone.parameters"
  action: "merge"
  value:
    drop_path_rate: 0.1
- path: "run.runner.train.optimization.optimizer.per_parameter.0.lr_decay_rate"
  value: 0.8