- path: "name"
  value: "DINOv2/L-224"
- path: "logging.tags"
  action: "remove"
  value: "base"
- path: "logging.tags"
  action: "append"
  value: "large"
- path: "model.backbone.parameters.name"
  value: "ViT-L/14"
- path: "model.backbone.parameters"
  action: "merge"
  value:
    drop_path_rate: 0.1
- path: "run.runner.train.optimization.optimizer.per_parameter.0.num_layers"
  value: 24
- path: "run.runner.train.optimization.optimizer.per_parameter.0.lr_decay_rate"
  value: 0.8
